### ISSUE TITLE
Cant see textures

### ISSUE THREAD

**Issue by ExonHUN** [shedaniel/Materialisation#37] opened 2020-07-27 14:27 UTC
![image](https://user-images.githubusercontent.com/59777466/88553813-0043cf00-d026-11ea-8828-7e1931d8ce72.png)

**Comment by shedaniel** [comment] 2020-07-27 14:32
sodium or optifine not compatible

**Comment by natsistd** [comment] 2020-07-27 16:12
> sodium or optifine not compatible

I was having the same issue. Is this something that needs to be fixed on Sodium's end?

**Comment by shedaniel** [comment] 2020-07-27 16:14
Correct, sodium doesn't support fabric rendering api, in turns breaks rendering of materialisation's dynamic tools

**Comment by shedaniel** [comment] 2020-07-29 14:19
Caused by https://github.com/jellysquid3/sodium-fabric/issues/5

**Closed as completed by shedaniel** 2020-07-29 14:19 UTC
